# Generated by Django 5.1 on 2024-08-29 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_image_tasks_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.tasks', verbose_name='image'),
        ),
    ]
