# Generated by Django 5.1 on 2024-10-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_image_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
