# Generated by Django 5.1 on 2024-10-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasks_image_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='image',
            new_name='images',
        ),
    ]
