# Generated by Django 5.1 on 2024-10-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_image_tasks_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='images',
            field=models.ImageField(null=True, upload_to='images', verbose_name='images'),
        ),
    ]
