# Generated by Django 5.1 on 2024-10-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_feed_feedfile_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedfile',
            old_name='file',
            new_name='images',
        ),
    ]
