# Generated by Django 5.1 on 2024-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_file_feedfile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedfile',
            name='images',
        ),
        migrations.AddField(
            model_name='feedfile',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
