# Generated by Django 5.1 on 2024-10-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_tasks_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedfile',
            name='tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.tasks', verbose_name='image'),
        ),
    ]
