# Generated by Django 5.1 on 2024-10-08 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_feedfile_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedFile',
            new_name='ImageFile',
        ),
    ]
