# Generated by Django 5.1 on 2024-10-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_rename_feedfile_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='due_date',
        ),
    ]
